### ISSUE TITLE
Error during installation for pip 9.0.3 with Python 2.7.12

### ISSUE THREAD

**Issue by mirfan899** [sequitur-g2p/sequitur-g2p#10]
python setup.py build
/home/irfan/.local/lib/python2.7/site-packages/setuptools/dist.py:406: UserWarning: The version specified ('perpetually-alpha') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running build
running build_ext
error: each element of 'ext_modules' option must be an Extension instance or 2-tuple
Makefile:6: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by langep** [comment]
I will be looking into it.

**Comment by jtrmal** [comment]
@langep patrick, while you are at it, could you just change https://github.com/sequitur-g2p/sequitur-g2p/blob/d71c436b5c2c3cb61b842cb42fadf2937c1f82de/setup.py#L117
to something that fits PEP404?

**Comment by jtrmal** [comment]
I've found  something that can be related here
https://github.com/pypa/setuptools/issues/309

@mirfan899 what OS are you using?

**Comment by langep** [comment]
I created a PR. Sorry for the closed ones I had still some old commits in my branch that were merged already.

**Comment by langep** [comment]
I was able to replicate and resolve but maybe @mirfan899 can test it with his setup too.

**Comment by langep** [comment]
Obsolete. Has been merged.

To test before the merge:
```
git clone https://github.com/langep/sequitur-g2p.git
cd sequitur-g2p
git checkout fix-pip-install-py2
python setup.py build
```

**Comment by mirfan899** [comment]
@jtrmal @langep Ok I will test it.

**Comment by mirfan899** [comment]
It works fine now. Thanks for quick response!!
