### ISSUE TITLE
failed to convert "word" :translation failed (for every for word in the dictionary

### ISSUE THREAD

**Issue by dragonsharma** [sequitur-g2p/sequitur-g2p#15]
i have build the model as per the documentation now my model have decent accuracy as per the test . but when i try to convert my words dictionary it show this error for every word 
"failed to convert "word" :translation failed (for every for word in the dictionary"
i am using python 2.7 on ubuntu 16.04
can anybody help me what is going on ?

**Comment by jtrmal** [comment]
Make sure you are using the same case, the same encoding, that the words
from the wordlist do not contain some special (invisible) character and so
on.
Also, while you say dictionary,  I assume you are providing a wordlist.
Y.

**Comment by dragonsharma** [comment]
thanks for your quick reply :+1:  
yes by dictionary here i mean wordlist . 
i will check this in detail and will come back to you .

**Comment by dragonsharma** [comment]
i found the error actually it was on my end i was using uppercase for training and lowercase for converting .
thanks for your input @jtrmal
