### ISSUE TITLE
Missing codecs import

### ISSUE THREAD

**Issue by Barker404** [sequitur-g2p/sequitur-g2p#17]
When running `g2p.py --train train.lex --devel 5% --write-model model-1` as in the README, I get an error:

    NameError: global name 'codecs' is not defined

It looks like 1eaf3a1753f8eb8573efaf42956ee269a494696a is missing an import for `codecs`.

**Comment by jtrmal** [comment]
Thanks for catching that -- weird thing it didnt cause problems in test.
Should be fixed by #18 and (via  01bd074)

**Comment by Barker404** [comment]
Thanks

**Comment by jtrmal** [comment]
give it a test and comment/reopen again, please, if it won't work
Thanks
y.
