### ISSUE TITLE
Thouble with training script (in github.com/freerussianasr/recipes)

### ISSUE THREAD

**Issue by hpkit** [sequitur-g2p/sequitur-g2p#19]
i try voxforge_ru recipe from https://github.com/freerussianasr/recipes

Add --encoding utf-8 from issue https://github.com/freerussianasr/recipes/issues/8 not work.

--- Preparing pronunciations for OOV words ...
Traceback (most recent call last):
File "/home/kaldi/kaldi/tools/sequitur-g2p/bin/g2p.py", line 4, in
import('pkg_resources').run_script('sequitur==1.0a1', 'g2p.py')
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 719, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 1504, in run_script
exec(code, namespace, namespace)
File "/home/kaldi/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/g2p.py", line 268, in
tool.run(main, options, args)
File "/home/kaldi/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/tool.py", line 63, in run
status = runMain(main, options, args)
File "/home/kaldi/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/tool.py", line 99, in runMain
status = main(options, args)
File "/home/kaldi/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/g2p.py", line 214, in main
mainApply(translator, options)
File "/home/kaldi/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/g2p.py", line 164, in mainApply
for word, left in words:
File "/home/kaldi/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur-1.0a1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/g2p.py", line 100, in readApply
for line in gOpenIn(fname, defaultEncoding):
File "/usr/lib/python2.7/codecs.py", line 630, in next
line = self.readline()
File "/usr/lib/python2.7/codecs.py", line 545, in readline
data = self.read(readsize, firstline=True)
File "/usr/lib/python2.7/codecs.py", line 488, in read
newdata = self.stream.read(size)
File "/usr/lib/python2.7/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 12: ordinal not in range(128)

File is utf-8 encoding and contains russian cyrillic symbols. I try use --encoding parameter, but it did not change the situation.
[vocab-oov.txt](https://github.com/sequitur-g2p/sequitur-g2p/files/2102618/vocab-oov.txt)

**Comment by jtrmal** [comment]
I don't think you have the current sequitur -- for me, it doesn't crash:
```
 $ cat vocab-oov.txt | g2p.py -V 0.9 --variants-number 3 --encoding utf-8 --model g2p.model.final --apply -
failed to convert "-pau-": translation failed
failed to convert "<unk>": translation failed
failed to convert "ждановскую": translation failed
failed to convert "живоносного": translation failed
failed to convert "заногу": translation failed
failed to convert "катюшиной": translation failed
failed to convert "кирпично": translation failed
failed to convert "лапчатой": translation failed
failed to convert "махновщина": translation failed
failed to convert "междузвёздном": translation failed
failed to convert "многоугольную": translation failed
failed to convert "монетную": translation failed
failed to convert "непостигаемые": translation failed
failed to convert "обсыпавшиеся": translation failed
failed to convert "поблескивала": translation failed
failed to convert "подвёртки": translation failed
failed to convert "подштаники": translation failed
failed to convert "потушено": translation failed
failed to convert "приколоченное": translation failed
failed to convert "притягиваемся": translation failed
failed to convert "проломанный": translation failed
failed to convert "прорезывал": translation failed
failed to convert "прудики": translation failed
failed to convert "пустившее": translation failed
failed to convert "рассыпающей": translation failed
failed to convert "реостатам": translation failed
failed to convert "скайлс": translation failed
failed to convert "скайльс": translation failed
failed to convert "скайльса": translation failed
failed to convert "тугоплавкой": translation failed
stack usage:  1
```
(the "translation failed" message is natural -- I don't have a russian model)

**Comment by jtrmal** [comment]
Can you send me an output of 
```
git log -1
```
command?
It should be issued in `/home/kaldi/kaldi/tools/sequitur-g2p`

**Comment by hpkit** [comment]
root@Ubuntu1:/home/kaldi/kaldi/tools/sequitur-g2p# git log -1
commit 01bd074966f8e71665ef8034edd03233e9ac2de3
Author: Jan "yenda" Trmal <jtrmal@gmail.com>
Date:   Tue Jun 12 07:29:54 2018 -0400

    add codecs import to the file (#18)

**Comment by jtrmal** [comment]
can you prepare a minimal working example? I'll try to have a detailed look
during weekend.
By minimal example, I mean the command (the g2p.py call you are using) and
all the necessary files.
y.

**Comment by hpkit** [comment]
command is:
g2p.py --model=conf/g2p_model --apply vocab-oov.txt > lexicon-oov.txt 

"g2p_model" i downloaded manually from sf.net 
I think the problem is in the wrong file.
[vocab-oov.txt](https://github.com/sequitur-g2p/sequitur-g2p/files/2106018/vocab-oov.txt)

**Comment by jtrmal** [comment]
send me the link to the model, please.
y.

**Comment by hpkit** [comment]
wget http://sourceforge.net/projects/kaldi/files/sequitur-model4 -O conf/g2p_model

**Comment by jtrmal** [comment]
ok, I've figured out the issue, now it doesn't crash, but it still does not
produce pronunciation -- I think you are using english g2p models.
y.

**Comment by jtrmal** [comment]
so there was (probably) a bug in sequitur you hit when you used a g2p model trained on CMU dict (i.e. for English)
```
failed to convert "<unk>": translation failed
WEATHER W EH DH ER
failed to convert "weather": translation failed
```
I'm closing this, because I cannot help you further -- you will have to obtain a proper g2p trained for Russian (or use a graphemic lexicon).
