### ISSUE TITLE
Example train.lex

### ISSUE THREAD

**Issue by AlJohri** [sequitur-g2p/sequitur-g2p#2]
Does anyone have an example `train.lex` file? Would be helpful for understanding the input format.

**Comment by giuliopaci** [comment]
It is a very simple format (the following is a snippet from working example):

petrifaction	p E t r x f @ k S x n
can	k @ n
can	k x n
exercise	E X R s A z

orthographic forms are separated from the phonetic transcriptions with tabs in this example, but I do not remember if it is mandatory.
As you can see, order does not prevent sequitur-g2p to complete its job. Homographs are allowed.
