### ISSUE TITLE
How i can use FST model with secuitur-g2p ?

### ISSUE THREAD

**Issue by hpkit** [sequitur-g2p/sequitur-g2p#21]
I found some g2p models for russian in FST format. How i can use it with --model parameter ?

**Comment by jtrmal** [comment]
you never provide enough information to answer the question -- for example,
I have no idea what did you find and where.
That being said, almost certainly you cannot use sequitur to do that -- it
has its own format.
If you have an fst transducer graphemes -> phonemes, then I guess it should
be fairly easy to use OpenFST to do that, but that assumes you have at
least some experience with fsts.
You would compile the input into a linear grapheme fst, composed with the
transducer and then just chose the best-path (or one-best).
y.

**Comment by hpkit** [comment]
Sorry...
These models were generated using Phonetisaurus Phonetisaurus and the GlobalPhone dataset. 
http://montreal-forced-aligner.readthedocs.io/en/stable/pretrained_models.html

How it convert to secuitur-g2p model...

**Comment by jtrmal** [comment]
All right, that's actually good news -- phonetisaurus is the same kind of
tool sequitur is and is much faster and better maintained.
So my suggestion is just to use the phonetisaurus to generate the
pronunciations.
The git repo is here: https://github.com/AdolfVonKleist/Phonetisaurus
y.

**Comment by hpkit** [comment]
If converting impossible... i try it. Thanks!
