### ISSUE TITLE
EditDistance function is not propery return.

### ISSUE THREAD

**Issue by lifefeel** [sequitur-g2p/sequitur-g2p#26]
Hi. I'm testing on python 3.5.
I found the function 'align' on `EditDistance.cc` is always return miss value.
I tested like below.

```
from sequitur_ import align

reference = ('K', 'AH0', 'Z')
candidate = ('K', 'AH0', 'Z')

alignment, errors = align(reference, candidate)

print(alignment, errors)
```
and then the return value is
```
[('K', 'K'), ('AH0', 'AH0'), ('Z', 'Z')] 3
```
Is this means sequence 'reference' and 'candidate' has 3 mis-matched?

**Comment by jtrmal** [comment]
yes, the function is not working right.
The fix is probably switching the costs in the substitution,
i.e. changing line 41 to
```
 41       return (PyObject_RichCompare(a, b, Py_EQ)) ? 0: 1;
```
but I'm not sure if it breaks something else or not -- it's an old software
and in those cases bugs slowly become features.
Could you please test it?
y.

**Comment by jtrmal** [comment]
Actually, the proposed fix didn't do what it was supposed to do. This seems
to work:
```
return (PyObject_RichCompareBool(a, b, Py_EQ)) == 1 ? 0 : 1; // can return
-1
```
The function PyObject_RichCompare returns a reference to either the left or
the right object -- we need the RichCompareBool function. I tested it on
two trivial tests and it seems to work -- still, could you please test it
more extensively?
Thanks
y.

**Comment by lifefeel** [comment]
I tested latest commit 9bef47be2ca5c0fac8b256c7a06db9f6b52355ff. It works well, thanks.

**Comment by jtrmal** [comment]
Happy to hear that, thanks.
