### ISSUE TITLE
Russian text & utf-8

### ISSUE THREAD

**Issue by JurPasha** [sequitur-g2p/sequitur-g2p#31]
Hello, jtrmal!
I'm trying to use sequitur for training Russian model. Vocab file is encoded in utf-8, so I have used --encoding='utf-8' key in all variants of g2p script running. When I run in such way:
g2p.py --encoding='utf-8' --model=$MyDo/models/model-$ver --apply $oovfile
It work ok and output results to the shell screen.
But when I'm trying to save results to the file:
g2p.py --encoding='utf-8' --model=$MyDo/models/model-$ver --apply $oovfile > lexicon-oov.txt
it gives me an error: UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
File with traceback attached
[error.txt](https://github.com/sequitur-g2p/sequitur-g2p/files/2301384/error.txt)

Jrtmal, please, can you guide me how to solve this problem?

**Comment by Lokhozt** [comment]
Hello,
I solved this problem by using python 3. instead of python 2. for french language.
`g2p.py --model MODEL_PATH --apply OVV_WORD.txt -e utf-8 > RESULT.txt` works fine now.

Cheers

**Comment by jtrmal** [comment]
@JurPasha should be resolved by the last commit, please test
