### ISSUE TITLE
Problem while training a model

### ISSUE THREAD

**Issue by vishalkumar9** [sequitur-g2p/sequitur-g2p#4]
I have run a command: $ g2p.py --train ../cmudict/train.txt --devel 5% --write-model model-1
And I am getting this error:

                                       Traceback (most recent call last):
  File "/usr/local/bin/g2p.py", line 38, in <module>
    import SequiturTool
  File "/usr/local/bin/SequiturTool.py", line 34, in <module>
    from sequitur import Sequitur, ModelTemplate, DefaultDiscountAdjuster, StaticDiscounts, FixedDiscounts, EagerDiscountAdjuster
  File "/usr/local/bin/sequitur.py", line 32, in <module>
    import sequitur_, SequenceModel, Minimization, misc
  File "/usr/local/bin/sequitur_.py", line 28, in <module>
    _sequitur_ = swig_import_helper()
  File "/usr/local/bin/sequitur_.py", line 20, in swig_import_helper
    import _sequitur_
ImportError: /home/vishal/Documents/Study/Exploratory_Project/g2p-Squitur/lib/python2.7/site-packages/_sequitur_.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm

Please help me with this error.

**Comment by jtrmal** [comment]
I cannot give you a specific answer.

When you demangle that symbol, it says
```
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)
```

the `__cxx11` namespace might be something for clang or newer vs older gcc or flags the python libs should have or should not have. But all relates to the way you compile vs how python was built.
HTH
y.

**Comment by jtrmal** [comment]
too old, without response, closing
