### ISSUE TITLE
Issue when installing on MacOS

### ISSUE THREAD

**Issue by amitection** [sequitur-g2p/sequitur-g2p#44]
When I run this command

`CPPFLAGS="-stdlib=libstdc++" pip install git+https://github.com/sequitur-g2p/sequitur-g2p@master`

I get the following error

```
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    sequitur_wrap.cpp:3057:10: fatal error: 'stdexcept' file not found
    #include <stdexcept>
             ^~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
```

So when I try the suggested `-std=libc++` 

```
In file included from sequitur_wrap.cpp:3147:
In file included from ./Multigram.hh:33:
./UnorderedMap.hh:26:10: fatal error: 'tr1/unordered_map' file not found
#include <tr1/unordered_map>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
error: command 'cc' failed with exit status 1
```

I do understand that this has something to do with the compiler versions. I have no experience in C / CPP. Please guide.

**Comment by jtrmal** [comment]
Can you send me output  from `gcc --version`?
y.

**Comment by amitection** [comment]
gcc --version

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

cc --version

```
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by jtrmal** [comment]
I have the same compiler and I can get it installed using this command:
CPPFLAGS="-stdlib=libc++" pip install git+
https://github.com/sequitur-g2p/sequitur-g2p@master

i.e. not std=libc++ but stdlib=libc++
(std is a completely different switch and I don't understand why they
recommend something like that).
y.

**Comment by amitection** [comment]
I too am not sure how to proceed on this. However, I'll try to fix this and post the solution here.

**Comment by jtrmal** [comment]
the worst case, you can manually delete the 'tr1', i.e. from
`<tr1/unordered_map>`
you do `<unordered_map>`
That will solve the problem for you, but I still don''t understand why it
should be an issue, there is a def line that should handle it.
y.

**Comment by hwiorn** [comment]
@amitection Could you test c++11 flag?
`tr1` is contains by stdlibc++ and prior to c++11.
~~~
CPPFLAGS="-std=c++11 -stdlib=libstdc++" pip install git+https://github.com/sequitur-g2p/sequitur-g2p@master
~~~

Check this https://stackoverflow.com/questions/42030598/mac-c-compiler-not-finding-tr1-unordered-map

Or the xcode include path may be broken. So, check your ENV variables too(e.g: bash profile)

**Comment by sharonwoo** [comment]
> I have the same compiler and I can get it installed using this command: CPPFLAGS="-stdlib=libc++" pip install git+ https://github.com/sequitur-g2p/sequitur-g2p@master i.e. not std=libc++ but stdlib=libc++ (std is a completely different switch and I don't understand why they recommend something like that). y.
> […](#)

This comment helped me, I was unable to use ```CPPFLAGS="-stdlib=libstdc++"``` but ```stdlib=libc++ ``` was fine. Running Mojave 10.14.6

**Comment by jtrmal** [comment]
perhaps you could use the pypi.org way to install it:
```
pip3 install -i https://test.pypi.org/simple/ sequitur-g2
```
anyway, closing, inactive for too long...
