### ISSUE TITLE
"translation failed" ERROR for only some words

### ISSUE THREAD

**Issue by byuns9334** [sequitur-g2p/sequitur-g2p#49]
Hi, I am running g2p.py for korean corpus, and I get this "failed to convert <word>: translation failed" error while applying on my test data.
![image](https://user-images.githubusercontent.com/26813646/62843245-5a536380-bcf3-11e9-8782-ea7a9eb62363.png)
The strange thing is that it occurs on some cases. Do you have any idea on why?

**Comment by jtrmal** [comment]
That normally happens when you present a word with a character not seen
during training. Typically it can be a rare character or some Unicode
specialties.
For your case, I don't see right away what character it could be, but I'd
suggest starting investigating in that direction.
Y.

**Comment by j0ma** [comment]
Interestingly, i had this happen with some Hebrew characters when transliterating Yiddish. 

What I did was take the words I trained on and used 
```
g2p.py --model <my_model> --apply seen_in_training.txt
 ```
to see what the output would look like. 

Weirdly enough, some words get transliterated just fine, while others get the same "failed to convert: translation failed" error mentioned by OP. See below for an example:

```
[...]
failed to convert "××× ××××": translation failed
failed to convert "× ×¢××¢×š××": translation failed
שריפֿטשטעלער	s h r i f t s h t e l e r
באַראָן	b a r o n
אַכטל	a k h t l
[...]
```

It does seem to me like the things `g2p.py` is trying to convert aren't even proper Hebrew characters. Is this a bug or a feature? Maybe I could simply integer-label the different characters and train a model for that representation?

**Comment by jtrmal** [comment]
I believe something will be wrong with your word list. FOr your case, it
seems the words contain space -- that should not happen.
If you will send me a small repro, I will try to have a look.
y.

**Comment by jtrmal** [comment]
I didn't get to test it yet, but can you make sure you use the appropriate
encoding parameter, so that the content of the files is interpreted
correctly?
y.

**Comment by jtrmal** [comment]
Plus, your format is incorrect -- at least two of the words contain spaces:
failed to convert "חול המועד": translation failed
failed to convert "עם הארץ": translation failed
y.

**Comment by j0ma** [comment]
The encoding flag seems to have done the trick! Thank you @jtrmal !

**Comment by jtrmal** [comment]
closing
