### ISSUE TITLE
Could someone better explain what the "--devel N%" switch controls/does?

### ISSUE THREAD

**Issue by zarquon5** [sequitur-g2p/sequitur-g2p#5]
I have followed the suggested example of using "--devel 5%" when building models, but I don't understand how this switch affects what happens.  (FTR, if you say --devel 100%, it will fail, but it will accept 99%, although it then becomes verrry slow).  The --help says "use N% of the training data", but this does not provide sufficient insight into what is happening, and leads me to the following questions:

1. The help text suggests that this might mean "make the training process only use N% of the training data when building the model;" if so, how does it pick which N% to pay attention to?
2. Also, if true, how does this sampling change (if at all) with subsequent training steps?  
3. If not true, then I don't understand what this means; can someone please better explain/elaborate?   
4. How does changing this parameter affect the training process and the resulting models?  
5. How would one determine an optimum value for this parameter?

AdvThanksance...

**Comment by jtrmal** [comment]
You will have to look at the sources or perhaps read the papers. I had assumed it's a random subset of the training data, selected only once in the beginning of training. But I have never checked.
