### ISSUE TITLE
how to use --transpose mode?

### ISSUE THREAD

**Issue by liliya-belaus** [sequitur-g2p/sequitur-g2p#6]
Did anyone succeed using --transpose mode? 
What should be the format of training and test data for it?
Should I use --transpose option on training or test step? 
I actually tried several variants and none of them worked for me.
An example of training and testing commands and data using transpose mode will be an ideal response

**Comment by jtrmal** [comment]
If you need help, then you have to be more careful in describing what is the issue, for example what "none of them worked" means. I didn't have problem with using that option.

**Comment by jtrmal** [comment]
too old, without response, closing
