### ISSUE TITLE
Script stops on downloading six

### ISSUE THREAD

**Issue by thw0ng** [sequitur-g2p/sequitur-g2p#66]
Hi, guys.

I have a problem during installation of Kaldi.
The problem is on stage of installing sequitur.
I just start the script and it stops working on step of downloading six, here is the log:

thread@tlaptop:~/Projects/ReHelper/kaldi/tools/extras$ ./install_sequitur.sh 
./install_sequitur.sh: Updating the repository -- we will try to merge with local changes (if you have any)
Already up-to-date.
python setup.py build
running build
running build_py
running build_ext
running build_scripts
USER SITE: /home/thread/.local/lib/python2.7/site-packages
SEQUITUR_PACKAGE: lib/python2.7/site-packages
SEQUITUR: /home/thread/Projects/ReHelper/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages
PYTHONPATH: 
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing requirements to sequitur_g2p.egg-info/requires.txt
writing sequitur_g2p.egg-info/PKG-INFO
writing top-level names to sequitur_g2p.egg-info/top_level.txt
writing dependency_links to sequitur_g2p.egg-info/dependency_links.txt
reading manifest file 'sequitur_g2p.egg-info/SOURCES.txt'
writing manifest file 'sequitur_g2p.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/SequenceModel.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/sequitur.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/tool.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/symbols.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/_sequitur_.so -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/g2p.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/Evaluation.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/Minimization.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/misc.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/SequiturTool.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/sequitur_.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/SequenceModel.py to SequenceModel.pyc
byte-compiling build/bdist.linux-x86_64/egg/sequitur.py to sequitur.pyc
byte-compiling build/bdist.linux-x86_64/egg/tool.py to tool.pyc
byte-compiling build/bdist.linux-x86_64/egg/symbols.py to symbols.pyc
byte-compiling build/bdist.linux-x86_64/egg/g2p.py to g2p.pyc
byte-compiling build/bdist.linux-x86_64/egg/Evaluation.py to Evaluation.pyc
byte-compiling build/bdist.linux-x86_64/egg/Minimization.py to Minimization.pyc
byte-compiling build/bdist.linux-x86_64/egg/misc.py to misc.pyc
byte-compiling build/bdist.linux-x86_64/egg/SequiturTool.py to SequiturTool.pyc
byte-compiling build/bdist.linux-x86_64/egg/sequitur_.py to sequitur_.pyc
creating stub loader for _sequitur_.so
byte-compiling build/bdist.linux-x86_64/egg/_sequitur_.py to _sequitur_.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/g2p.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/g2p.py to 775
copying sequitur_g2p.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sequitur_g2p.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sequitur_g2p.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sequitur_g2p.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sequitur_g2p.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
sequitur_: module references __file__
creating 'dist/sequitur_g2p-1.0.1668.6-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing sequitur_g2p-1.0.1668.6-py2.7-linux-x86_64.egg
removing '/home/thread/Projects/ReHelper/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur_g2p-1.0.1668.6-py2.7-linux-x86_64.egg' (and everything under it)
creating /home/thread/Projects/ReHelper/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur_g2p-1.0.1668.6-py2.7-linux-x86_64.egg
Extracting sequitur_g2p-1.0.1668.6-py2.7-linux-x86_64.egg to /home/thread/Projects/ReHelper/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages
sequitur-g2p 1.0.1668.6 is already the active version in easy-install.pth
Installing g2p.py script to /home/thread/Projects/ReHelper/kaldi/tools/sequitur-g2p/bin

Installed /home/thread/Projects/ReHelper/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur_g2p-1.0.1668.6-py2.7-linux-x86_64.egg
Processing dependencies for sequitur-g2p==1.0.1668.6
Searching for six>=1.11.0
Reading https://pypi.python.org/simple/six/
Best match: six 1.15.0
Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz#sha256=30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259

So it stays here forever.
I am new in this all python and so on stuff, please help.

**Comment by jtrmal** [comment]
you could try to install it manually before running the sequitur install
pip install six\>=1.11.0
or
pip2 install six\>=1.11.0
but I kinda doubt that will be the reason
y.

**Comment by thw0ng** [comment]
Doesn't help.
The problem I guess in downloading.
I don't know python and bash enough to understand what the installation script does.
It stays on downloading step. If I press Ctrl-C it informs me that process was interrupted:
...
Installed /home/thread/Projects/ReHelper/kaldi/tools/sequitur-g2p/lib/python2.7/site-packages/sequitur_g2p-1.0.1668.6-py2.7-linux-x86_64.egg
Processing dependencies for sequitur-g2p==1.0.1668.6
Searching for six>=1.11.0
Reading https://pypi.python.org/simple/six/
Best match: six 1.15.0
Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz#sha256=30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259
^Cinterrupted
Problem installing sequitur!

**Comment by jtrmal** [comment]
wait, before running the script, did you execute the pip install six
command?
What did it do?
y.

**Comment by thw0ng** [comment]
I tried uninstall six and install back, there is no any effect.
Just now:
thread@tlaptop:~/Projects/ReHelper/kaldi/tools/extras$ pip install --user six
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: six in /home/thread/.local/lib/python2.7/site-packages (1.15.0)
thread@tlaptop:~/Projects/ReHelper/kaldi/tools/extras$

**Comment by jtrmal** [comment]
That's weird. Most probably not your fault but. You could just delete the "six" line from the requirements.txt file

**Comment by thw0ng** [comment]
Ok. Can you please give me the path to requirements.txt (I am using Ubuntu 16.04)?

**Comment by thw0ng** [comment]
Got it! Sequitur installed successfully :) Thank you, @jtrmal

**Comment by jtrmal** [comment]
glad it has helped and sorry I wasnt specific about the location of the file
