### ISSUE TITLE
Publishing the wheels in pypi

### ISSUE THREAD

**Issue by akshayc11** [sequitur-g2p/sequitur-g2p#67]
Hi,
I was wondering if there is any possibility of publishing wheels for python 3.x across platforms for this package in https://pypi.org/ ?
I saw that some wheels were available in https://test.pypi.org/project/sequitur-g2p/ , but it would be good for my team's workflow if this could be made an official package within pypi proper.

If you wish, we have interested stakeholders within my company who are willing to fork this repository, do the necessary legwork for building the wheels for latest versions of python (3.x) for at-least the platforms we need it to work on (Mac osX and manylinux), but it would be ideal for having this done by the maintainers of the original repo.

Please reach out to me if you have any questions or concerns with either approach.

Thanks,
[Akshay Chandrashekaran](mailto:achandrashekaran@twilio.com)

**Comment by jtrmal** [comment]
Hi, yeah, I plan to do it in the near future...
I'm also open to consider any modifications to the existing pipeline to
make this happen automatically.
y.

**Comment by jtrmal** [comment]
Hi, as I said I'm willing to review/accept anyone's PR (i.e. help) -- that
still holds :) I didn't get to it yet, so there is not "progress hidden
somewhere"...
Or do you have some other ideas on your mind? Please let me know
y.

**Comment by swenson** [comment]
Oh, cool. I might take a look at it. :) I just wanted to double-check with you first.

**Comment by jtrmal** [comment]
Perfect -- I will be grateful.
What I was imagining was having a tag of a specific format (release-X... or
pypi-X) and after creation of the tag it would get compiled and pushed...
Most of the infrastructure already exists, I believe, in .travis.yml
y.

**Comment by jtrmal** [comment]
resolved by #69
