### ISSUE TITLE
Issue with Russian lexicon

### ISSUE THREAD

**Issue by pikaliov** [sequitur-g2p/sequitur-g2p#7]
I trained model sequintur with Russian lexicon:

> а aa
> а(2) a
> аадниель a ay d nn i j je ll
> аадниэль aa ay d nn i ll
> ааз aa ay s
> ааза a a z aa
> аазом a a z oo m

and when i tested with some words:

> а-а
> абрикосовая
> агитпоезда
> аиу
> атанора
> атанору
> ашхе

I got strange symbols in 1st words in the string:

> Ð°-Ð°	aa
> Ð°Ð±ÑÐžÐºÐŸÑÐŸÐ²Ð°Ñ	a b rr i k a s ay v ay i
> Ð°Ð³ÐžÑÐ¿ÐŸÐµÐ·ÐŽÐ°	a gg ii t p a j je z d ay
> Ð°ÐžÑ	a ii u
> Ð°ÑÐ°ÐœÐŸÑÐ°	a t aa n ay r ay
> Ð°ÑÐ°ÐœÐŸÑÑ	a t aa n ay r u
> Ð°ÑÑ	

I don't know the reason of this problem. Can you help?

**Comment by jtrmal** [comment]
perhaps you could check if you specified the right encoding both during training and during test

**Comment by pikaliov** [comment]
yes, you are right. Perhaps problem with wrong encoding in output (save to txt). There is no problem in console output:
> дети 	dd i tt i
> дело	dd je l ay
But  
> �	ватит	v aa tt ii t
should be 
> хватит  hh v aa tt ii t
I stoped on training  model-4. If I will train higher models i will get rid of this wrong symbol or not? 
Thank you for quick response.

**Comment by jtrmal** [comment]
I have problems seeing your encoding so I'm not sure which symbol you are talking about? Do you mean 'hh' in the beginning of the pronunciation? That one might go away when you do more iterations. But it's kinda expected that the g2p does mistakes, especially for irregular pronunciations. I think that going to 5 or even 6 won't give you too much of an improvement, but you can definitely try.

**Comment by jtrmal** [comment]
too old without any response, closing
