### ISSUE TITLE
github actions upload fails on windows

### ISSUE THREAD

**Issue by jtrmal** [sequitur-g2p/sequitur-g2p#73]
@swenson I wonder if you'd have time to address the fact that the container actions work only on linux?
I'd assume we can still install twine and upload using that on macos and windows?
Please let me know if you are up to it (and if you need something from me -- I thnk I'm ok to make you a collaborator or something)

**Comment by swenson** [comment]
Sure, I can take a look this week.

**Comment by swenson** [comment]
I think the PyPI token is not set to the production token?

> It looks like you are trying to use an API token to authenticate in the package index and your token value does not start with "pypi-" as it typically should.

**Comment by jtrmal** [comment]
sorry, I just generated a new one -- perhaps last time I messed up
somehthing
y.

**Comment by swenson** [comment]
Alright, after a few more iterations, I got them all published! https://pypi.org/project/sequitur-g2p/#files

**Comment by jtrmal** [comment]
amazing!  thanks a lot!
y.
