### ISSUE TITLE
Translation always fails

### ISSUE THREAD

**Issue by Corasonn** [sequitur-g2p/sequitur-g2p#75]
I tried many models. I built my own with the german dictionary from [here](https://github.com/gooofy/zamia-speech) and also used the prebuild model. Furthermore I tried it with [this model](https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/) (hidden in "Option B – the more fun, DIY way"), but when I want to use the model, the translation always fails for each word.

`g2p.py --model model-tutorial.key --encoding=utf-8 --apply words.txt > result.txt`

words.txt:
```
Hello
Test
apple
table
dog
cat
potatoe
```

I use python 3.9.5 on MacOS 10.15.7.

Can anybody help me what is going on?

**Comment by jtrmal** [comment]
I'm not familiar with that model(s) but make sure the model does not expect
only upper-case or lower-case words (casing generally does. not influence
pronunciation, so it's often times unified).
y.

**Comment by Corasonn** [comment]
Oh, that works! Thank you very much, @jtrmal! You saved my day 🙏 :)

For the model from the tutorial, the words need to be totally uppercased
```
HELLO
TEST
APPLE
TABLE
DOG
CAT
POTATOE
```

For the Zamia models, they must be lowercased (I tried it before with german words with first letter uppercased)
```
hallo
test
```

**Comment by jtrmal** [comment]
glad to hear it.  please close the issue.
y.
