### ISSUE TITLE
Calculate the posterior value of given translation

### ISSUE THREAD

**Issue by treya-lin** [sequitur-g2p/sequitur-g2p#76]
Hi. I am wondering if it is possible for the model to calculate the posterior value for a given translation. 

For example, I have a wordlist with give phonemic transcriptions and a model. For now, the model can give me the posterior values if I apply it to a word list (need to set 'variants-number'). But in the python codes, I didn't figure out how to feed it with some given trancriptions and let the model calculate how reliable those transcriptions are. Thanks for any suggestions! I'm new to this field :D

**Comment by treya-lin** [comment]
For example, if I give the model a word "cat", the model could generate something like:
cat 0 0.8 K AE T
cat 1 0.125 K AX T

but I hope to find a way to give it something like
cat K EH T
cat K AX T

and then the model calculates the posterior values based on the transcriptions I give it, and returns something like
cat 0 0.188 K EH T
cat 0 0.125 K AX T

Hope I made my question clear :D

**Comment by jtrmal** [comment]
Unfortunately, I don't see any way how to do it robustly.
Heuristically, you could generate like first 100 pronunciations and try to
find it in those (with the associated prob). If not in that 100 prons, then
assign 0.
After that, renormalize the probs.
y.

**Comment by treya-lin** [comment]
I see. Thank you 😂

**Comment by jtrmal** [comment]
closing :)
