### ISSUE TITLE
Is there a pure C++ Version of this G2P Toolkit available . 

### ISSUE THREAD

**Issue by kerolos** [sequitur-g2p/sequitur-g2p#77]
I would like to know if you implement a full C++ version of this toolkit. because I would like to integrate that to my C++ research project.

**Comment by jtrmal** [comment]
well, there is certainly not an example of it, but the core is already in C++, so it might be reasonably straightforward.
Another option that is completely C++ is Phonetisaurus (https://github.com/AdolfVonKleist/Phonetisaurus). Plus that tool has much faster training process.

**Comment by kerolos** [comment]
thanks for your reply, I just want to use it only for inference (decoding mode). but I got this error when loading the saved model (I have trained models in a different python version p2.7 , p3.6 ) in C++ using pickle lib (Caught exception: Don't know how to handle I or,  or V ,or X ). 
error in : PicklingTools170Release/C++/pickleloader.h
 "
case PY_INST:         NOT_IMPLEMENTED('i'); break;  // 'i'    
case PY_UNICODE:       NOT_IMPLEMENTED('V'); // 'V'
case PY_BINUNICODE:    NOT_IMPLEMENTED('X'); // 'X' 
"
Do you know how can i load the model in C++ OR what is the equivalent function in c++ to this function"model = pickle.load(open(self.options.modelFile, 'rb'), encoding='latin1')" ?

I am going to try this Phonetisaurus toolkit. Do you think, can I obtain the same level of accuracy as in sequitur toolkit specially in German G2P?

**Comment by jtrmal** [comment]
I'm pretty sure the performance would be comparable if not better. G2P is a
fairly easy task.
y.

**Comment by kerolos** [comment]
Sorry for bothering you again. 
i have tried the recommended toolkit "Phonetisaurus " with the same German Lexicon. unfortunately the result is worse compare to sequitur:
Sequitur:           PER :1.718 ,  WER: 7.858
Phonetisaurus:  PER : 2.742 , WER: 14.413
as my understanding of Phonetisaurus toolkit. it does almost the same process as Sequitur. 
I would really appreciate if you can explain to me why the performance of Sequitur (specially in German Lexicon) is very impressive compare to other toolkits and Algorithms such as Phonetisaurus , Seq2Seq g2p , and  LSTM DL, Multitask Learning g2p ,BERT ?
