### ISSUE TITLE
pip install fails with missing `requirements.txt`

### ISSUE THREAD

**Issue by dhdaines** [sequitur-g2p/sequitur-g2p#98]
The `setup.py` in the published tar.gz package on PyPI (sequitur-g2p-1.0.1668.22.tar.gz) looks for a `requirements.txt` file but it is not there.

So installing from source fails (no matter what build system you use).

Suggest that you make a new release which includes this file (since it's in the git repository, after all...)

**Comment by jtrmal** [comment]
thanks! I will merge today

**Comment by jtrmal** [comment]
resolved via #101
